# Generated by Django 2.2.16 on 2022-11-03 11:05

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MODERATOR', 'moderator'), ('USER', 'user')], default=users.utils.Role('user'), max_length=9, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username='me'), name='Username_is_not_me'),
        ),
    ]
