# Generated by Django 2.2.16 on 2022-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221104_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cofirmation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
    ]
